services:
  - type: web
    name: filestream-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_HASH
        value: your_api_hash_here
      - key: API_ID
        value: your_api_id_here
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: DATABASE_URL
        value: your_database_url_here
      - key: SESSION_STRING
        value: your_pyrogram_session_string
